env: production
port: 4000
logs:
  level: 'silly'

path_prefix: ''

database:
  user: root
  password: changeme
  host: 172.25.0.3
  port: 3306
  dialect: mysql

barong:
  jwt_public_key: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1dGVVckpTVC9XaGpRcE52R1ZrZApHa215KzNMcXVSanNUbzJvcEIwRlNTNGtoem9QV0p3ZHZhcDNrbkpxMGdSUHNTb1NCc3lvbFZKSkxQdWU3NlpiCjVaSklzV0k0eTZuWjlMalBWenFlTlR5T25BUzVHczJBdFRaZnN4QnlCRGYxVTJ6dDI3Rkk2dEI1a2hmSjUzYXoKSTVXMzlxTSs5K08zRnFPMlM5VHNDeXppTDVSQ1dFVlBXQWlJdGZZZlFBOHZRR2dQK0hvTHJNRUZLWUxFRkpocwpIdGdINnhTVzNXbFA1aW5YZUxvM0tyMGYzNUlIUzRna296YTF5TEw1bTE1a0NIZmtVSDJDT1pyT3l2R2loY3EvCksyaXF4RzlIK3RJVXlqV1lIcDVQbUxlT0VubzNXa1gzd1E2NlhnVXpKYWNFWUVtSGVIanVRQjZHUWVCaFdsSWoKeVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=='

vault:
  address: http://172.25.0.4:8200
  token: s.QwAeIO1nIp92ew2etYhdzxpu
  app_name: xeni

waiting-time-minutes-loop: 15
#15 concurrently
amount-concurrently-run: 15
